/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package techpesc.telas;

import java.text.ParseException;
import techpesc.relogio.Relogio;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import techpesc.alimentacao.Alimentacao;
import techpesc.alimentacao.AlimentacaoDAO;
import techpesc.alimentacao.AlimentacaoTableModel;
import techpesc.estoque.racao.Racao;
import techpesc.estoque.racao.RacaoDAO;
import techpesc.estoque.racao.RacaoRN;
import techpesc.estoque.racao.RacaoTableModel;
import techpesc.lote.Lote;
import techpesc.lote.LoteDAO;
import techpesc.lote.LoteTableModel;
import techpesc.tanquerede.TanqueRede;
import techpesc.tanquerede.TanqueRedeDAO;
import techpesc.tanquerede.TanqueRedeTableModel;
import techpesc.transfereTR.Transferencia;
import techpesc.transfereTR.TransferenciaDAO;
import techpesc.transfereTR.TransferenciaTableModel;
import techpesc.util.Util;

/**
 *
 * @author fatima
 */
public class CadastroAlimentarTanqueRede extends javax.swing.JDialog {

    Lote lote = new Lote();
    Transferencia transferencia = new Transferencia();
    TanqueRedeDAO tanqueredeDAO = new TanqueRedeDAO();
    Alimentacao alimentacao = new Alimentacao();
    AlimentacaoDAO alimentacaoDAO = new AlimentacaoDAO();
    List<Double> alimentacaoFeita = new ArrayList<>();
    Racao racao;
    RacaoDAO racaoDAO = new RacaoDAO();
    RacaoRN racaoRN = new RacaoRN();
    List<TanqueRede> listaTanqueRedesAlimentados = new ArrayList<>();
    TransferenciaDAO transferenciaDAO = new TransferenciaDAO();
    List<TanqueRede> tanqueRedesLote = new ArrayList<>();
    List<TanqueRede> tanqueSemAlteracao = new ArrayList<>();
    List<Lote> listadeLotes = new ArrayList<>();
    List<TanqueRede> tanqueRedesNovoTR = new ArrayList<>();
    SimpleDateFormat formatar = new SimpleDateFormat("dd/MM/yyyy hh:mm");
    Date data = new Date();
    Date dataAtual = new Date();

    /**
     * Creates new form Cadastro_de_Funcionário
     */
    public CadastroAlimentarTanqueRede() {
        initComponents();
        this.setIconImage(new ImageIcon(getClass().getResource("/techpesc/imagens/peixe.png")).getImage());
        setModal(true);
        limparCampos();
        mostrarHora();
        jLPrincipal.setLayout(null);

    }

    public void mostrarHora() {
        Relogio ah = new Relogio(tfHora);
        ah.mostrarData(true);
        Thread thHora = ah;
        thHora.start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLPrincipal = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator17 = new javax.swing.JSeparator();
        jPanel2 = new javax.swing.JPanel();
        btPesquisar = new javax.swing.JButton();
        btVoltarMenu = new javax.swing.JButton();
        btSalvar = new javax.swing.JButton();
        btSalvar1 = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel42 = new javax.swing.JLabel();
        tfNomeLote = new javax.swing.JTextField();
        btPesquisarNome4 = new javax.swing.JButton();
        btAlimentar = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tbTanqueRedeLote = new javax.swing.JTable();
        jScrollPane4 = new javax.swing.JScrollPane();
        tbTanqueRedeNovoTR = new javax.swing.JTable();
        jLabel43 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        tfHora = new javax.swing.JLabel();
        jLabel45 = new javax.swing.JLabel();
        tfRacao = new javax.swing.JTextField();
        btPesquisarNome5 = new javax.swing.JButton();
        btCadastroLote = new javax.swing.JButton();
        btCadastroEstoque = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Alimentação de Peixe");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(23, 49, 106));
        jPanel1.setToolTipText("");

        jLPrincipal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/techpesc/imagens/cabeçalho1.png"))); // NOI18N
        jLPrincipal.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Alimentação de Peixes");

        jPanel2.setBackground(new java.awt.Color(23, 49, 106));
        jPanel2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        btPesquisar.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btPesquisar.setForeground(new java.awt.Color(255, 255, 255));
        btPesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/techpesc/imagens/pesquisa.png"))); // NOI18N
        btPesquisar.setText("Pesquisar");
        btPesquisar.setToolTipText("");
        btPesquisar.setContentAreaFilled(false);
        btPesquisar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btPesquisar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btPesquisar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btPesquisarActionPerformed(evt);
            }
        });

        btVoltarMenu.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btVoltarMenu.setForeground(new java.awt.Color(255, 255, 255));
        btVoltarMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/techpesc/imagens/voltar.png"))); // NOI18N
        btVoltarMenu.setText("Voltar");
        btVoltarMenu.setToolTipText("");
        btVoltarMenu.setContentAreaFilled(false);
        btVoltarMenu.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btVoltarMenu.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btVoltarMenu.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btVoltarMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btVoltarMenuActionPerformed(evt);
            }
        });

        btSalvar.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btSalvar.setForeground(new java.awt.Color(255, 255, 255));
        btSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/techpesc/imagens/salvar.png"))); // NOI18N
        btSalvar.setText("Salvar");
        btSalvar.setToolTipText("");
        btSalvar.setContentAreaFilled(false);
        btSalvar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btSalvar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btSalvar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSalvarActionPerformed(evt);
            }
        });

        btSalvar1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btSalvar1.setForeground(new java.awt.Color(255, 255, 255));
        btSalvar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/techpesc/imagens/novo.png"))); // NOI18N
        btSalvar1.setText("Novo");
        btSalvar1.setToolTipText("");
        btSalvar1.setContentAreaFilled(false);
        btSalvar1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btSalvar1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btSalvar1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btSalvar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSalvar1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(btVoltarMenu)
                .addGap(197, 197, 197)
                .addComponent(btSalvar1, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46)
                .addComponent(btSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btPesquisar)
                .addGap(13, 13, 13))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 586, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 3, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btSalvar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btVoltarMenu, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(btPesquisar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btSalvar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
        );

        jLabel42.setFont(new java.awt.Font("Calibri", 1, 20)); // NOI18N
        jLabel42.setForeground(new java.awt.Color(255, 255, 255));
        jLabel42.setText("Lote.:");

        tfNomeLote.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        tfNomeLote.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfNomeLoteActionPerformed(evt);
            }
        });

        btPesquisarNome4.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btPesquisarNome4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/techpesc/imagens/sub_pesquisar.png"))); // NOI18N
        btPesquisarNome4.setContentAreaFilled(false);
        btPesquisarNome4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btPesquisarNome4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btPesquisarNome4ActionPerformed(evt);
            }
        });

        btAlimentar.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btAlimentar.setForeground(new java.awt.Color(255, 255, 255));
        btAlimentar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/techpesc/imagens/icone_alimentacao.png"))); // NOI18N
        btAlimentar.setText("Alimentar");
        btAlimentar.setContentAreaFilled(false);
        btAlimentar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btAlimentar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btAlimentar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btAlimentar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAlimentarActionPerformed(evt);
            }
        });

        tbTanqueRedeLote.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        tbTanqueRedeLote.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Tanques Rede"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbTanqueRedeLote.setRowSelectionAllowed(false);
        tbTanqueRedeLote.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                tbTanqueRedeLoteFocusLost(evt);
            }
        });
        tbTanqueRedeLote.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbTanqueRedeLoteMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tbTanqueRedeLote);

        tbTanqueRedeNovoTR.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        tbTanqueRedeNovoTR.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Tanques Rede"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbTanqueRedeNovoTR.setRowSelectionAllowed(false);
        tbTanqueRedeNovoTR.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                tbTanqueRedeNovoTRFocusLost(evt);
            }
        });
        tbTanqueRedeNovoTR.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbTanqueRedeNovoTRMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(tbTanqueRedeNovoTR);

        jLabel43.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel43.setForeground(new java.awt.Color(255, 255, 255));
        jLabel43.setText("T.R. Alimentados.:");

        jLabel44.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel44.setForeground(new java.awt.Color(255, 255, 255));
        jLabel44.setText("T.R. Não Alimentados.:");

        tfHora.setBackground(new java.awt.Color(102, 255, 102));
        tfHora.setFont(new java.awt.Font("Calibri", 2, 14)); // NOI18N
        tfHora.setForeground(new java.awt.Color(255, 255, 255));
        tfHora.setText("hora.:");

        jLabel45.setFont(new java.awt.Font("Calibri", 1, 20)); // NOI18N
        jLabel45.setForeground(new java.awt.Color(255, 255, 255));
        jLabel45.setText("Ração.:");

        tfRacao.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        tfRacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfRacaoActionPerformed(evt);
            }
        });

        btPesquisarNome5.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btPesquisarNome5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/techpesc/imagens/sub_pesquisar.png"))); // NOI18N
        btPesquisarNome5.setContentAreaFilled(false);
        btPesquisarNome5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btPesquisarNome5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btPesquisarNome5ActionPerformed(evt);
            }
        });

        btCadastroLote.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btCadastroLote.setForeground(new java.awt.Color(255, 255, 255));
        btCadastroLote.setIcon(new javax.swing.ImageIcon(getClass().getResource("/techpesc/imagens/sub_cadastrar.png"))); // NOI18N
        btCadastroLote.setContentAreaFilled(false);
        btCadastroLote.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btCadastroLote.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btCadastroLote.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btCadastroLote.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCadastroLoteActionPerformed(evt);
            }
        });

        btCadastroEstoque.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btCadastroEstoque.setForeground(new java.awt.Color(255, 255, 255));
        btCadastroEstoque.setIcon(new javax.swing.ImageIcon(getClass().getResource("/techpesc/imagens/sub_cadastrar.png"))); // NOI18N
        btCadastroEstoque.setContentAreaFilled(false);
        btCadastroEstoque.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btCadastroEstoque.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btCadastroEstoque.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btCadastroEstoque.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCadastroEstoqueActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel44)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btAlimentar)
                        .addGap(27, 27, 27)
                        .addComponent(jLabel43)
                        .addGap(123, 123, 123))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addGap(9, 9, 9)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jSeparator17, javax.swing.GroupLayout.PREFERRED_SIZE, 586, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(212, 212, 212)
                        .addComponent(jLabel1)
                        .addGap(47, 47, 47)
                        .addComponent(tfHora))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(114, 114, 114)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel45)
                            .addComponent(jLabel42))
                        .addGap(12, 12, 12)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tfRacao)
                            .addComponent(tfNomeLote, javax.swing.GroupLayout.DEFAULT_SIZE, 193, Short.MAX_VALUE))
                        .addGap(2, 2, 2)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(btPesquisarNome5, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btCadastroEstoque, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(btPesquisarNome4, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btCadastroLote, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLPrincipal)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(13, 13, 13))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(tfHora)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addComponent(jSeparator17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(btPesquisarNome4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(tfNomeLote, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel42))
                    .addComponent(btCadastroLote, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btPesquisarNome5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(tfRacao, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel45))
                    .addComponent(btCadastroEstoque, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 61, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel43)
                            .addComponent(jLabel44))
                        .addGap(8, 8, 8))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btAlimentar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents


    private void btSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSalvarActionPerformed
        if (transferencia == null) {
            transferencia = new Transferencia();
        }
        if (Util.chkVazio(tfNomeLote.getText(), tfRacao.getText()) == true) {
            if ((!listaTanqueRedesAlimentados.isEmpty()) && (transferencia.getIdTransferencia() == 0)) {
                for (int i = 0; i < listaTanqueRedesAlimentados.size(); i++) {
                    lote.setTanquesRede(tanqueSemAlteracao);
                    alimentacao.setLote(lote);
                    alimentacao.setRacao(racao);
                    alimentacao.setIdAlimentacao(listaTanqueRedesAlimentados.get(i).getIdTanqueRede());
                    alimentacao.setNomeTanqueRede(listaTanqueRedesAlimentados.get(i).getNomeTanqueRede());
                    alimentacao.setQuantidadeAlimentacao(alimentacaoFeita.get(i));
                    try {
                        dataAtual = formatar.parse(formatar.format(data));
                    } catch (ParseException ex) {
                        Logger.getLogger(CadastroCliente.class.getName()).log(Level.SEVERE, null, ex);
                    }
                    alimentacao.setDataAlimentacao(dataAtual);
                    alimentacaoDAO.salvar(alimentacao);
                    alimentacao.setIdAlimentacao(Short.valueOf("0"));
                }
                JOptionPane.showMessageDialog(rootPane, "Pronto, a alimentação dos tanques redes selecionados foram realizadas com sucesso!");
                limparCampos();
            } else {
                JOptionPane.showMessageDialog(rootPane, "Só é possível salvar uma alimentação se houver algum tanque alimentado!",
                        "ERRO", JOptionPane.ERROR_MESSAGE);

            }
        }


    }//GEN-LAST:event_btSalvarActionPerformed
    public void limparCampos() {
        lote = new Lote();
        transferencia = new Transferencia();
        racao = new Racao();
        tfNomeLote.setText("");
        tfRacao.setText("");
        tanqueRedesLote.clear();
        tanqueRedesNovoTR.clear();
        tanqueSemAlteracao.clear();
        listadeLotes.clear();
        tanqueRedesNovoTR.clear();
        listaTanqueRedesAlimentados.clear();
        btSalvar.setEnabled(true);
        transferencia = null;
        lote = null;
        racao = null;
        atualizaTabelaTanqueRedeLote();
        atualizaTabelaTanqueRedeNovoTR();
    }

    private void btVoltarMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btVoltarMenuActionPerformed

        dispose();
    }//GEN-LAST:event_btVoltarMenuActionPerformed

    private void btSalvar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSalvar1ActionPerformed
        limparCampos();        // TODO add your handling code here:
    }//GEN-LAST:event_btSalvar1ActionPerformed

    private void tfNomeLoteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfNomeLoteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfNomeLoteActionPerformed

    private void btPesquisarNome4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btPesquisarNome4ActionPerformed
        LoteDAO loteDAO = new LoteDAO();
        lote = new Lote();

        LoteTableModel loteTableModel = new LoteTableModel(loteDAO.listar());
        Object object = TelaConsulta.exibeTela(loteTableModel, "Lotes");        // TODO add your handling code here:
        Short codigo = Short.valueOf(String.valueOf(object));
        lote = loteDAO.pesquisarCodigo(codigo);
        tfNomeLote.setText(lote.getNomeLote());
        tanqueSemAlteracao.addAll(lote.getTanquesRede());

        tanqueRedesLote = lote.getTanquesRede();

        atualizaTabelaTanqueRedeLote();
    }//GEN-LAST:event_btPesquisarNome4ActionPerformed

    private void atualizaTabelaTanqueRedeLote() {
        TanqueRedeTableModel atm = new TanqueRedeTableModel(tanqueRedesLote);
        tbTanqueRedeLote.setModel(atm);
    }

    private void atualizaTabelaTanqueRedeNovoTR() {
        TanqueRedeTableModel atm = new TanqueRedeTableModel(tanqueRedesNovoTR);
        tbTanqueRedeNovoTR.setModel(atm);
    }
    private void btPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btPesquisarActionPerformed
        List<Alimentacao> lista;
        AlimentacaoDAO dao = new AlimentacaoDAO();
        lista = (dao.listar());
        AlimentacaoTableModel itm = new AlimentacaoTableModel(lista);
        Object o = TelaConsulta.exibeTela(itm, "Alimentação");
        if (o != null) {
            alimentacao = dao.pesquisarCodigo(Short.valueOf(String.valueOf(o)));
            tfNomeLote.setText(alimentacao.getLote().getNomeLote());
            tfRacao.setText(alimentacao.getRacao().getDescricaoOutros());
            tanqueRedesLote = alimentacao.getLote().getTanquesRede();
            lote = alimentacao.getLote();
            atualizaTabelaTanqueRedeLote();
            atualizaTabelaTanqueRedeNovoTR();
            btSalvar.setEnabled(false);

        }
    }//GEN-LAST:event_btPesquisarActionPerformed

    private void btAlimentarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAlimentarActionPerformed
        Alimentacao alimentacaoTemporaria = new Alimentacao();
        Double quantidade = 0.0;
        int row = tbTanqueRedeLote.getSelectedRow();
        if (lote != null) {
            if (racao != null) {
                if (row > -1) {
                    if (JOptionPane.showConfirmDialog(null, "Você deseja realmente alimentar os peixes do Tanque Rede: " + tanqueRedesLote.get(tbTanqueRedeLote.getSelectedRow()).getNomeTanqueRede()
                            + " ?", "TechPesc", JOptionPane.YES_NO_OPTION, JOptionPane.INFORMATION_MESSAGE) == JOptionPane.YES_OPTION) {
                        String valor = (JOptionPane.showInputDialog("Peso da ração selecionada disponível: " + racao.getPesoRacao() + " Kg\n\n"
                                + "Digite o peso que será usado para alimentar o Tanque Rede: " + tanqueRedesLote.get(tbTanqueRedeLote.getSelectedRow()).getNomeTanqueRede() + "\n\n"
                                + "Vale ressaltar que o peso informado deve ser em Kg, ou seja, se quiser \n"
                                + "adicionar 500gramas o peso que deverá ser informado é: 0.5", "0.0"));
                        if (!valor.isEmpty()) {
                            quantidade = Double.parseDouble(valor);
                            if (quantidade <= racao.getPesoRacao()) {
                                if ((quantidade > 0.0)) {
                                    listaTanqueRedesAlimentados.add(tanqueRedesLote.get(tbTanqueRedeLote.getSelectedRow()));
                                    tanqueRedesNovoTR.add(tanqueRedesLote.get(tbTanqueRedeLote.getSelectedRow()));
                                    tanqueRedesLote.remove(tanqueRedesLote.get(tbTanqueRedeLote.getSelectedRow()));
                                    alimentacaoFeita.add(quantidade);
                                    racao.setPesoRacao(racao.getPesoRacao() - quantidade);
                                    atualizaTabelaTanqueRedeNovoTR();
                                    atualizaTabelaTanqueRedeLote();
                                } else {
                                    JOptionPane.showMessageDialog(rootPane, "O valor digitado para ração da alimentação do Tanque foi 0.0, sendo assim, nenhum T.R foi alimentado!",
                                            "ERRO", JOptionPane.INFORMATION_MESSAGE);
                                }
                            } else {
                                JOptionPane.showMessageDialog(rootPane, "O peso digitado de ração para alimentar os T.R foi: " + quantidade + " Kg\n\n"
                                        + "Porém só há em estoque: " + racao.getPesoRacao() + " Kg\n\n"
                                        + "Favor, digitar um valor compatível com oque há no estoque!",
                                        "ERRO", JOptionPane.ERROR_MESSAGE);
                            }
                        } else {
                            JOptionPane.showMessageDialog(rootPane, "Não foi digitado o valor do peso da ração para alimentar o T.R, sendo assim, nenhum T.R foi alimentado!",
                                    "ERRO", JOptionPane.ERROR_MESSAGE);
                        }
                    } else {
                        JOptionPane.showMessageDialog(rootPane, "A alimentação de tanques não foi realizada!",
                                "ERRO", JOptionPane.ERROR_MESSAGE);
                    }

                } else {
                    JOptionPane.showMessageDialog(rootPane, "Selecione o Tanque Rede!",
                            "ERRO", JOptionPane.ERROR_MESSAGE);
                }
            } else {
                JOptionPane.showMessageDialog(rootPane, "É obrigatório vincular uma ração!",
                        "ERRO", JOptionPane.ERROR_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(rootPane, "É obrigatório vincular um lote!",
                    "ERRO", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_btAlimentarActionPerformed

    private void tbTanqueRedeLoteFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tbTanqueRedeLoteFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_tbTanqueRedeLoteFocusLost

    private void tbTanqueRedeLoteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbTanqueRedeLoteMouseClicked
        if (evt.getClickCount() == 2) {
            btAlimentarActionPerformed(null);
        }
    }//GEN-LAST:event_tbTanqueRedeLoteMouseClicked

    private void tbTanqueRedeNovoTRFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tbTanqueRedeNovoTRFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_tbTanqueRedeNovoTRFocusLost

    private void tbTanqueRedeNovoTRMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbTanqueRedeNovoTRMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tbTanqueRedeNovoTRMouseClicked

    private void tfRacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfRacaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfRacaoActionPerformed

    private void btPesquisarNome5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btPesquisarNome5ActionPerformed
        List<Racao> listaRacao;
        racao = new Racao();
        listaRacao = (racaoDAO.listar());
        RacaoTableModel itmRacao = new RacaoTableModel(listaRacao);
        Object oRacao = TelaConsulta.exibeTela(itmRacao, "Racao");
        if (oRacao != null) {
            racao = racaoRN.pesquisarCodigo(Short.valueOf(String.valueOf(oRacao)));
            tfRacao.setText(racao.getDescricaoOutros());
        }
    }//GEN-LAST:event_btPesquisarNome5ActionPerformed

    private void btCadastroLoteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCadastroLoteActionPerformed
        new CadastroLote().setVisible(true);
    }//GEN-LAST:event_btCadastroLoteActionPerformed

    private void btCadastroEstoqueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCadastroEstoqueActionPerformed
        new CadastroEstoque().setVisible(true);
    }//GEN-LAST:event_btCadastroEstoqueActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastroAlimentarTanqueRede.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastroAlimentarTanqueRede.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastroAlimentarTanqueRede.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastroAlimentarTanqueRede.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastroAlimentarTanqueRede().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAlimentar;
    private javax.swing.JButton btCadastroEstoque;
    private javax.swing.JButton btCadastroLote;
    private javax.swing.JButton btPesquisar;
    private javax.swing.JButton btPesquisarNome4;
    private javax.swing.JButton btPesquisarNome5;
    private javax.swing.JButton btSalvar;
    private javax.swing.JButton btSalvar1;
    private javax.swing.JButton btVoltarMenu;
    private javax.swing.JLabel jLPrincipal;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JSeparator jSeparator17;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTable tbTanqueRedeLote;
    private javax.swing.JTable tbTanqueRedeNovoTR;
    private javax.swing.JLabel tfHora;
    private javax.swing.JTextField tfNomeLote;
    private javax.swing.JTextField tfRacao;
    // End of variables declaration//GEN-END:variables

}
