/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package techpesc.telas;

import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import techpesc.funcionario.Funcionario;
import techpesc.funcionario.FuncionarioDAO;
import techpesc.funcionario.FuncionarioTableModel;
import techpesc.lote.Lote;
import techpesc.lote.LoteDAO;
import techpesc.lote.LoteTableModel;
import techpesc.mortandade.Mortandade;
import techpesc.mortandade.MortandadeDAO;
import techpesc.mortandade.MortandadeTableModel;
import techpesc.tanquerede.TanqueRede;
import techpesc.tanquerede.TanqueRedeTableModel;
import techpesc.util.Util;

/**
 *
 * @author fatima
 */
public class CadastroMortandade extends javax.swing.JDialog {

    Lote lote = new Lote();
    List<TanqueRede> tanqueRedes = new ArrayList<>();
    Mortandade mortandade = new Mortandade();
    MortandadeDAO mortandadeDAO = new MortandadeDAO();
    SimpleDateFormat formatar = new SimpleDateFormat("dd/MM/yyyy hh:mm");
    Date data = new Date();
    Date dataAtual = new Date();
    List<TanqueRede> listaTanquesMortos = new ArrayList<>();

    /**
     * Creates new form Cadastro_de_Funcionário
     */
    public CadastroMortandade() {
        initComponents();
        this.setIconImage(new ImageIcon(getClass().getResource("/techpesc/imagens/peixe.png")).getImage());
        setModal(true);
        limparCampos();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        racao1 = new techpesc.estoque.racao.Racao();
        racao2 = new techpesc.estoque.racao.Racao();
        racao3 = new techpesc.estoque.racao.Racao();
        jPanel1 = new javax.swing.JPanel();
        jLabel41 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator17 = new javax.swing.JSeparator();
        jPanel2 = new javax.swing.JPanel();
        btPesquisar = new javax.swing.JButton();
        btVoltarMenu = new javax.swing.JButton();
        btSalvar = new javax.swing.JButton();
        btSalvar1 = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel42 = new javax.swing.JLabel();
        tfNomeLote = new javax.swing.JTextField();
        btPesquisarNome4 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbTanqueRede = new javax.swing.JTable();
        btMortandade = new javax.swing.JButton();
        btCadastroLote = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Registro de Mortandade");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(23, 49, 106));
        jPanel1.setToolTipText("");

        jLabel41.setIcon(new javax.swing.ImageIcon(getClass().getResource("/techpesc/imagens/cabeçalho1.png"))); // NOI18N

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Mortandade T.R.");

        jPanel2.setBackground(new java.awt.Color(23, 49, 106));

        btPesquisar.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btPesquisar.setForeground(new java.awt.Color(255, 255, 255));
        btPesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/techpesc/imagens/pesquisa.png"))); // NOI18N
        btPesquisar.setText("Pesquisar");
        btPesquisar.setToolTipText("");
        btPesquisar.setContentAreaFilled(false);
        btPesquisar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btPesquisar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btPesquisar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btPesquisarActionPerformed(evt);
            }
        });

        btVoltarMenu.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btVoltarMenu.setForeground(new java.awt.Color(255, 255, 255));
        btVoltarMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/techpesc/imagens/voltar.png"))); // NOI18N
        btVoltarMenu.setText("Voltar");
        btVoltarMenu.setToolTipText("");
        btVoltarMenu.setContentAreaFilled(false);
        btVoltarMenu.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btVoltarMenu.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btVoltarMenu.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btVoltarMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btVoltarMenuActionPerformed(evt);
            }
        });

        btSalvar.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btSalvar.setForeground(new java.awt.Color(255, 255, 255));
        btSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/techpesc/imagens/salvar.png"))); // NOI18N
        btSalvar.setText("Salvar");
        btSalvar.setToolTipText("");
        btSalvar.setContentAreaFilled(false);
        btSalvar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btSalvar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btSalvar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSalvarActionPerformed(evt);
            }
        });

        btSalvar1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btSalvar1.setForeground(new java.awt.Color(255, 255, 255));
        btSalvar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/techpesc/imagens/novo.png"))); // NOI18N
        btSalvar1.setText("Novo");
        btSalvar1.setToolTipText("");
        btSalvar1.setContentAreaFilled(false);
        btSalvar1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btSalvar1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btSalvar1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btSalvar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSalvar1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(btVoltarMenu)
                .addGap(192, 192, 192)
                .addComponent(btSalvar1, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(btSalvar)
                .addGap(18, 18, 18)
                .addComponent(btPesquisar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(22, 22, 22))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 586, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 3, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btSalvar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btVoltarMenu, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(btPesquisar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btSalvar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
        );

        jLabel42.setFont(new java.awt.Font("Calibri", 1, 20)); // NOI18N
        jLabel42.setForeground(new java.awt.Color(255, 255, 255));
        jLabel42.setText("Lote.:");

        tfNomeLote.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        tfNomeLote.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfNomeLoteActionPerformed(evt);
            }
        });

        btPesquisarNome4.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btPesquisarNome4.setForeground(new java.awt.Color(255, 255, 255));
        btPesquisarNome4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/techpesc/imagens/sub_pesquisar.png"))); // NOI18N
        btPesquisarNome4.setContentAreaFilled(false);
        btPesquisarNome4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btPesquisarNome4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btPesquisarNome4.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btPesquisarNome4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btPesquisarNome4ActionPerformed(evt);
            }
        });

        tbTanqueRede.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        tbTanqueRede.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Tanques Rede"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbTanqueRede.setRowSelectionAllowed(false);
        tbTanqueRede.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                tbTanqueRedeFocusLost(evt);
            }
        });
        tbTanqueRede.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbTanqueRedeMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tbTanqueRede);

        btMortandade.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btMortandade.setForeground(new java.awt.Color(255, 255, 255));
        btMortandade.setIcon(new javax.swing.ImageIcon(getClass().getResource("/techpesc/imagens/icone_mortandade.png"))); // NOI18N
        btMortandade.setText("Mortandade");
        btMortandade.setContentAreaFilled(false);
        btMortandade.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btMortandade.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btMortandade.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btMortandade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btMortandadeActionPerformed(evt);
            }
        });

        btCadastroLote.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btCadastroLote.setForeground(new java.awt.Color(255, 255, 255));
        btCadastroLote.setIcon(new javax.swing.ImageIcon(getClass().getResource("/techpesc/imagens/sub_cadastrar.png"))); // NOI18N
        btCadastroLote.setContentAreaFilled(false);
        btCadastroLote.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btCadastroLote.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btCadastroLote.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btCadastroLote.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCadastroLoteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel41, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jSeparator17, javax.swing.GroupLayout.PREFERRED_SIZE, 586, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(228, 228, 228)
                        .addComponent(jLabel1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 488, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(61, 61, 61))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(btMortandade)
                        .addGap(248, 248, 248))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(133, 133, 133)
                        .addComponent(jLabel42)
                        .addGap(12, 12, 12)
                        .addComponent(tfNomeLote, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btPesquisarNome4, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btCadastroLote, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel41)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addGap(13, 13, 13)
                .addComponent(jSeparator17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(btPesquisarNome4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(tfNomeLote, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel42))
                    .addComponent(btCadastroLote, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btMortandade)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 235, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents


    private void btSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSalvarActionPerformed
        if (mortandade == null) {
            mortandade = new Mortandade();
        }
        if (Util.chkVazio(tfNomeLote.getText()) == true) {
        if (mortandade.getIdMortandade() == 0) {
            for (int i = 0; i < listaTanquesMortos.size(); i++) {
                mortandade.setLote(lote);
                try {
                    dataAtual = formatar.parse(formatar.format(data));
                } catch (ParseException ex) {
                    Logger.getLogger(CadastroCliente.class.getName()).log(Level.SEVERE, null, ex);
                }
                mortandade.setIdTanqueRede(listaTanquesMortos.get(i).getIdTanqueRede());
                mortandade.setMortandadeTanqueRede(listaTanquesMortos.get(i).getMortandadeTanqueRede());
                mortandade.setNomeTanqueRede(listaTanquesMortos.get(i).getNomeTanqueRede());
                mortandade.setQuantidadePeixesVinculados(listaTanquesMortos.get(i).getQuantidadePeixesVinculados());
                mortandade.setDataMortandade(dataAtual);
                mortandadeDAO.salvar(mortandade);
                mortandade.setIdMortandade(Short.valueOf("0"));
            }
            JOptionPane.showMessageDialog(rootPane, "Mortandade salva com Sucesso!");
            limparCampos();
        } else {
            if (JOptionPane.showConfirmDialog(rootPane, "Deseja realmente editar o Lote " + lote.getNomeLote()
                    + "?", "TechPesc", JOptionPane.YES_NO_OPTION, JOptionPane.INFORMATION_MESSAGE) == JOptionPane.YES_OPTION) {
                for (int i = 0; i < tanqueRedes.size(); i++) {
                    mortandade.setLote(lote);
                    try {
                        dataAtual = formatar.parse(formatar.format(data));
                    } catch (ParseException ex) {
                        Logger.getLogger(CadastroCliente.class.getName()).log(Level.SEVERE, null, ex);
                    }
                    mortandade.setIdTanqueRede(tanqueRedes.get(i).getIdTanqueRede());
                    mortandade.setMortandadeTanqueRede(tanqueRedes.get(i).getMortandadeTanqueRede());
                    mortandade.setNomeTanqueRede(tanqueRedes.get(i).getNomeTanqueRede());
                    mortandade.setQuantidadePeixesVinculados(tanqueRedes.get(i).getQuantidadePeixesVinculados());
                    mortandade.setDataMortandade(dataAtual);
                    mortandadeDAO.salvar(mortandade);
          
                }
                JOptionPane.showMessageDialog(rootPane, "Pronto,  " + lote.getNomeLote()
                        + ", foi editado com sucesso!", "Tanque Rede", JOptionPane.INFORMATION_MESSAGE);
            }
            limparCampos();
        }
        }
    }//GEN-LAST:event_btSalvarActionPerformed
    public void limparCampos() {
        lote = new Lote();
        tfNomeLote.setText("");
        tanqueRedes.clear();
        atualizaTabelaTanqueRede();
        listaTanquesMortos.clear();
    }

    private void btVoltarMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btVoltarMenuActionPerformed

        dispose();
    }//GEN-LAST:event_btVoltarMenuActionPerformed

    private void btSalvar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSalvar1ActionPerformed
        limparCampos();        // TODO add your handling code here:
    }//GEN-LAST:event_btSalvar1ActionPerformed

    private void tfNomeLoteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfNomeLoteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfNomeLoteActionPerformed

    private void btPesquisarNome4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btPesquisarNome4ActionPerformed
        LoteDAO loteDAO = new LoteDAO();
        lote = new Lote();
        LoteTableModel loteTableModel = new LoteTableModel(loteDAO.listar());
        Object object = TelaConsulta.exibeTela(loteTableModel, "Lotes");        // TODO add your handling code here:
        Short codigo = Short.valueOf(String.valueOf(object));
        lote = loteDAO.pesquisarCodigo(codigo);
        tfNomeLote.setText(lote.getNomeLote());
        tanqueRedes = lote.getTanquesRede();
        atualizaTabelaTanqueRede();
    }//GEN-LAST:event_btPesquisarNome4ActionPerformed

    private void tbTanqueRedeFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tbTanqueRedeFocusLost

    }//GEN-LAST:event_tbTanqueRedeFocusLost

    private void atualizaTabelaTanqueRede() {
        TanqueRedeTableModel atm = new TanqueRedeTableModel(tanqueRedes);
        tbTanqueRede.setModel(atm);
    }

    private void tbTanqueRedeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbTanqueRedeMouseClicked
        if (evt.getClickCount() == 2) {
            btMortandadeActionPerformed(null);
        }
    }//GEN-LAST:event_tbTanqueRedeMouseClicked

    private void btPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btPesquisarActionPerformed
        List<Mortandade> lista;
        MortandadeDAO dao = new MortandadeDAO();
        lista = (dao.listar());
        MortandadeTableModel itm = new MortandadeTableModel(lista);
        Object o = TelaConsulta.exibeTela(itm, "Mortandade");
        if (o != null) {
            mortandade = dao.pesquisarCodigo(Short.valueOf(String.valueOf(o)));
            tfNomeLote.setText(mortandade.getLote().getNomeLote());
            tanqueRedes = mortandade.getLote().getTanquesRede();
            lote=mortandade.getLote();
            atualizaTabelaTanqueRede();

        }
    }//GEN-LAST:event_btPesquisarActionPerformed

    private void btMortandadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btMortandadeActionPerformed
        int row = tbTanqueRede.getSelectedRow();
        if (row > -1) {
            int peixesMortos = Integer.parseInt(JOptionPane.showInputDialog("Digite a quantidade de Peixes que morreram"));
            if (peixesMortos >= tanqueRedes.get(tbTanqueRede.getSelectedRow()).getMortandadeTanqueRede() - tanqueRedes.get(tbTanqueRede.getSelectedRow()).getLimiteAlevinosTanqueRede()) {
                if (peixesMortos <= tanqueRedes.get(tbTanqueRede.getSelectedRow()).getQuantidadePeixesVinculados()) {
                    tanqueRedes.get(tbTanqueRede.getSelectedRow()).setMortandadeTanqueRede(peixesMortos + tanqueRedes.get(tbTanqueRede.getSelectedRow()).getMortandadeTanqueRede());
                    listaTanquesMortos.add(tanqueRedes.get(tbTanqueRede.getSelectedRow()));
                    calculaMortandade(peixesMortos);
                } else {
                    JOptionPane.showMessageDialog(rootPane, "Não é possível inserir essa quantidade de peixes mortos,\npois é maior que a quantidade contida no tanque", "ERRO", JOptionPane.ERROR_MESSAGE);
                }
                atualizaTabelaTanqueRede();
            } else {
                JOptionPane.showMessageDialog(rootPane, "O número digitado ultrapassa o limite do tanque rede!", "ERRO", JOptionPane.ERROR_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(rootPane, "Selecione o Tanque Rede!",
                    "ERRO", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_btMortandadeActionPerformed

    private void btCadastroLoteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCadastroLoteActionPerformed
        new CadastroLote().setVisible(true);
    }//GEN-LAST:event_btCadastroLoteActionPerformed

    private void calculaMortandade(int peixes) {
        int qtdPeixesVivos = tanqueRedes.get(tbTanqueRede.getSelectedRow()).getQuantidadePeixesVinculados();
        tanqueRedes.get(tbTanqueRede.getSelectedRow()).setQuantidadePeixesVinculados(qtdPeixesVivos - peixes);

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastroMortandade.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastroMortandade.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastroMortandade.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastroMortandade.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastroMortandade().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btCadastroLote;
    private javax.swing.JButton btMortandade;
    private javax.swing.JButton btPesquisar;
    private javax.swing.JButton btPesquisarNome4;
    private javax.swing.JButton btSalvar;
    private javax.swing.JButton btSalvar1;
    private javax.swing.JButton btVoltarMenu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator17;
    private javax.swing.JSeparator jSeparator2;
    private techpesc.estoque.racao.Racao racao1;
    private techpesc.estoque.racao.Racao racao2;
    private techpesc.estoque.racao.Racao racao3;
    private javax.swing.JTable tbTanqueRede;
    private javax.swing.JTextField tfNomeLote;
    // End of variables declaration//GEN-END:variables

}
