/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package techpesc.telas;

import java.util.ArrayList;
import java.util.List;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import techpesc.funcionario.Funcionario;
import techpesc.funcionario.FuncionarioDAO;
import techpesc.funcionario.FuncionarioTableModel;
import techpesc.usuario.Usuario;
import techpesc.usuario.UsuarioDAO;
import techpesc.usuario.UsuarioRN;
import techpesc.usuario.UsuarioTableModel;

/**
 *
 * @author PC
 */
public class CadastroUsuario extends javax.swing.JDialog {

    Usuario usuario = new Usuario();
    UsuarioDAO usuarioDAO = new UsuarioDAO();
    UsuarioRN usuarioRN = new UsuarioRN();
    Funcionario funcionario;
    List<Usuario> usuarios = new ArrayList<>();

    public CadastroUsuario() {
        initComponents();
        this.setIconImage(new ImageIcon(getClass().getResource("/techpesc/imagens/peixe.png")).getImage());
        limparCampos();
        tfFuncionario.setEditable(false);
        setModal(true);
        usuarios = usuarioDAO.listar();
        if (usuarios.isEmpty()) {
            tfFuncionario.setVisible(false);
            btPesquisarFuncionario.setVisible(false);
            jLFuncionario.setVisible(false);
            cbAdministrador.setEnabled(false);
            cbAdministrador.setSelected(true);
        } else {

        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel41 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator17 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jPanel2 = new javax.swing.JPanel();
        jButton3 = new javax.swing.JButton();
        btSalvar = new javax.swing.JButton();
        btPesquisar = new javax.swing.JButton();
        btExcluir3 = new javax.swing.JButton();
        btSalvar2 = new javax.swing.JButton();
        tfUsuario = new javax.swing.JTextField();
        jLabel44 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        cbAdministrador = new javax.swing.JCheckBox();
        tfSenha = new javax.swing.JPasswordField();
        tfConfirmaSenha = new javax.swing.JPasswordField();
        tfFuncionario = new javax.swing.JTextField();
        btPesquisarFuncionario = new javax.swing.JButton();
        jLFuncionario = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastro de Usuário");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(23, 49, 106));

        jLabel41.setIcon(new javax.swing.ImageIcon(getClass().getResource("/techpesc/imagens/cabeçalho1.png"))); // NOI18N

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Cadastro de Usuário");

        jPanel2.setBackground(new java.awt.Color(23, 49, 106));

        jButton3.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/techpesc/imagens/voltar.png"))); // NOI18N
        jButton3.setText("Voltar");
        jButton3.setToolTipText("Voltar pro menu principal");
        jButton3.setContentAreaFilled(false);
        jButton3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton3.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        btSalvar.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btSalvar.setForeground(new java.awt.Color(255, 255, 255));
        btSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/techpesc/imagens/salvar.png"))); // NOI18N
        btSalvar.setText("Salvar");
        btSalvar.setToolTipText("Clique aqui para salvar");
        btSalvar.setContentAreaFilled(false);
        btSalvar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btSalvar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btSalvar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSalvarActionPerformed(evt);
            }
        });

        btPesquisar.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btPesquisar.setForeground(new java.awt.Color(255, 255, 255));
        btPesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/techpesc/imagens/pesquisa.png"))); // NOI18N
        btPesquisar.setText("Pesquisar");
        btPesquisar.setToolTipText("Clique aqui para pesquisar");
        btPesquisar.setContentAreaFilled(false);
        btPesquisar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btPesquisar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btPesquisar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btPesquisarActionPerformed(evt);
            }
        });

        btExcluir3.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btExcluir3.setForeground(new java.awt.Color(255, 255, 255));
        btExcluir3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/techpesc/imagens/excluir2.png"))); // NOI18N
        btExcluir3.setText("Excluir");
        btExcluir3.setToolTipText("Clique aqui para excluir");
        btExcluir3.setContentAreaFilled(false);
        btExcluir3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btExcluir3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btExcluir3.setPreferredSize(new java.awt.Dimension(57, 35));
        btExcluir3.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btExcluir3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btExcluir3ActionPerformed(evt);
            }
        });

        btSalvar2.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btSalvar2.setForeground(new java.awt.Color(255, 255, 255));
        btSalvar2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/techpesc/imagens/novo.png"))); // NOI18N
        btSalvar2.setText("Novo");
        btSalvar2.setToolTipText("Clique para limpar todos os campos");
        btSalvar2.setContentAreaFilled(false);
        btSalvar2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btSalvar2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btSalvar2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btSalvar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSalvar2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addComponent(jButton3)
                .addGap(177, 177, 177)
                .addComponent(btSalvar2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(btSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btExcluir3, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btSalvar2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btSalvar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btPesquisar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btExcluir3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        tfUsuario.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        tfUsuario.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                tfUsuarioFocusLost(evt);
            }
        });

        jLabel44.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel44.setForeground(new java.awt.Color(255, 255, 255));
        jLabel44.setText("Usuário.:");

        jLabel43.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel43.setForeground(new java.awt.Color(255, 255, 255));
        jLabel43.setText("Senha.: ");

        jLabel42.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel42.setForeground(new java.awt.Color(255, 255, 255));
        jLabel42.setText("Confirmar Senha.:");

        cbAdministrador.setBackground(new java.awt.Color(23, 49, 106));
        cbAdministrador.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        cbAdministrador.setForeground(new java.awt.Color(255, 255, 255));
        cbAdministrador.setText(" Administrador");
        cbAdministrador.setToolTipText("Permissão do usuário");

        tfSenha.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tfSenha.setToolTipText("Digite sua senha!");

        tfConfirmaSenha.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tfConfirmaSenha.setToolTipText("Repita a senha novamente!");

        tfFuncionario.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        tfFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfFuncionarioActionPerformed(evt);
            }
        });

        btPesquisarFuncionario.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btPesquisarFuncionario.setForeground(new java.awt.Color(255, 255, 255));
        btPesquisarFuncionario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/techpesc/imagens/sub_pesquisar.png"))); // NOI18N
        btPesquisarFuncionario.setContentAreaFilled(false);
        btPesquisarFuncionario.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btPesquisarFuncionario.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btPesquisarFuncionario.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btPesquisarFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btPesquisarFuncionarioActionPerformed(evt);
            }
        });

        jLFuncionario.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLFuncionario.setForeground(new java.awt.Color(255, 255, 255));
        jLFuncionario.setText("Funcionário.:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jSeparator17)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20))
                    .addComponent(jSeparator2)))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel41)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(212, 212, 212))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel44)
                                .addComponent(jLabel43)
                                .addComponent(jLabel42))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(tfSenha)
                                .addComponent(tfUsuario)
                                .addComponent(tfConfirmaSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(112, 112, 112))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(142, 142, 142)
                            .addComponent(cbAdministrador)
                            .addGap(212, 212, 212)))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLFuncionario)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tfFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btPesquisarFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(78, 78, 78))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel41)
                .addGap(5, 5, 5)
                .addComponent(jLabel1)
                .addGap(4, 4, 4)
                .addComponent(jSeparator17, javax.swing.GroupLayout.PREFERRED_SIZE, 4, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel44)
                    .addComponent(tfUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel43))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfConfirmaSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel42))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btPesquisarFuncionario)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(tfFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLFuncionario)))
                .addGap(4, 4, 4)
                .addComponent(cbAdministrador, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    public void limparCampos() {
        tfUsuario.setText("");
        tfConfirmaSenha.setText("");
        tfSenha.setText("");
        tfFuncionario.setText("");
        cbAdministrador.setSelected(false);
        btExcluir3.setEnabled(false);
        usuario = null;
    }
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed

        dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void btSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSalvarActionPerformed
        if (usuario == null) {
            usuario = new Usuario();
        }

        if (usuarioRN.validaSenha(tfSenha.getText(), tfConfirmaSenha.getText()) == false) {
            JOptionPane.showMessageDialog(null, "As senhas não conferem, redigite-as");
        } else {
            if ((usuarioDAO.pesquisarLogin(tfUsuario.getText()) != null) && (usuario.getIdUsuario() == 0)) {
                JOptionPane.showMessageDialog(null, "O usuário informado já está cadastrado, por favor, utilize um login diferente!");
            } else {
                if (usuario.getIdUsuario() == 0) {
                    usuario.setLogin(tfUsuario.getText());
                    usuario.setSenha(tfSenha.getText());
                    usuario.setAdministrador(cbAdministrador.isSelected());
                    usuario.setFuncionario(funcionario);
                    usuarioDAO.salvar(usuario);
                    JOptionPane.showMessageDialog(rootPane, "Usuário Cadastrado com Sucesso!");
                    limparCampos();

                } else {
                    usuario.setLogin(tfUsuario.getText());
                    usuario.setSenha(tfSenha.getText());
                    usuario.setAdministrador(cbAdministrador.isSelected());
                    if (usuario.getFuncionario().getNomeFuncionario() == null) {
                        usuario.setFuncionario(funcionario);
                    } else {
                        usuario.setFuncionario(usuario.getFuncionario());
                    }
                    usuarioDAO.salvar(usuario);
                    if (JOptionPane.showConfirmDialog(rootPane, "Deseja realmente editar o Usuário " + usuario.getLogin()
                            + "?", "TechPesc", JOptionPane.YES_NO_OPTION, JOptionPane.INFORMATION_MESSAGE) == JOptionPane.YES_OPTION) {
                        usuarioDAO.salvar(usuario);
                        JOptionPane.showMessageDialog(rootPane, "Pronto,  " + usuario.getLogin()
                                + ", foi editado com sucesso!", "Usuário", JOptionPane.INFORMATION_MESSAGE);
                    }
                    limparCampos();
                }
            }
        }

    }//GEN-LAST:event_btSalvarActionPerformed

    private void btPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btPesquisarActionPerformed
        List<Usuario> lista;
        lista = (usuarioDAO.listar());
        UsuarioTableModel itm = new UsuarioTableModel(lista);
        Object o = TelaConsulta.exibeTela(itm, "Usuário");
        if (o != null) {
            usuario = usuarioRN.pesquisarCodigo(Short.valueOf(String.valueOf(o)));
            tfUsuario.setText(usuario.getLogin());
            tfSenha.setText("");
            tfConfirmaSenha.setText("");
            cbAdministrador.setSelected(usuario.isAdministrador());
            if (usuario.getFuncionario() == null) {
                tfFuncionario.setVisible(false);
                btPesquisarFuncionario.setVisible(false);
                jLFuncionario.setVisible(false);
            } else {
                tfFuncionario.setVisible(true);
                btPesquisarFuncionario.setVisible(true);
                jLFuncionario.setVisible(true);
                tfFuncionario.setText(usuario.getFuncionario().getNomeFuncionario());
            }
            btExcluir3.setEnabled(true);
        }
    }//GEN-LAST:event_btPesquisarActionPerformed

    private void btExcluir3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btExcluir3ActionPerformed
        if (usuario != null) {
            if (usuario.getIdUsuario() != 0) {
                if (JOptionPane.showConfirmDialog(rootPane, "Deseja excluir o Usuário " + usuario.getLogin()
                        + "?", "TechPesc", JOptionPane.YES_NO_OPTION, JOptionPane.INFORMATION_MESSAGE) == JOptionPane.YES_OPTION) {
                    if (usuarioRN.remove(usuario)) {
                        JOptionPane.showMessageDialog(rootPane, "Pronto,  " + usuario.getLogin()
                                + ", foi excluído com sucesso!", "Usuário", JOptionPane.INFORMATION_MESSAGE);
                    } else {
                        JOptionPane.showMessageDialog(rootPane, "Não foi possível excluir o Usuário "
                                + usuario.getLogin(),
                                "Erro ao Excluir", JOptionPane.ERROR_MESSAGE);
                    }
                }
            }
        }
        limparCampos();
    }//GEN-LAST:event_btExcluir3ActionPerformed

    private void btSalvar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSalvar2ActionPerformed
        limparCampos();
    }//GEN-LAST:event_btSalvar2ActionPerformed

    private void tfFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfFuncionarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfFuncionarioActionPerformed

    private void btPesquisarFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btPesquisarFuncionarioActionPerformed
        FuncionarioDAO funcionarioDAO = new FuncionarioDAO(null);
        funcionario = new Funcionario();
        FuncionarioTableModel funcionarioTableModel = new FuncionarioTableModel(funcionarioDAO.listar());
        Object object = TelaConsulta.exibeTela(funcionarioTableModel, "Fornecedores");        // TODO add your handling code here:
        Short codigo = Short.valueOf(String.valueOf(object));
        funcionario = funcionarioDAO.pesquisarCodigo(codigo);
        tfFuncionario.setText(funcionario.getNomeFuncionario());
    }//GEN-LAST:event_btPesquisarFuncionarioActionPerformed

    private void tfUsuarioFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfUsuarioFocusLost

        List<Usuario> usuarios = new ArrayList<>();

        usuarios = usuarioDAO.listar();
        for (int i = 0; i < usuarios.size(); i++) {
            if (tfUsuario.getText().equals(usuarios.get(i).getLogin())) {
                JOptionPane.showMessageDialog(rootPane, "Já existe um funcionário com este usuário, use outro!",
                        "ERRO", JOptionPane.ERROR_MESSAGE);
                tfUsuario.setText("");
                tfUsuario.requestFocus();

            }
        }
    }//GEN-LAST:event_tfUsuarioFocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastroUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastroUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastroUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastroUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastroUsuario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btExcluir3;
    private javax.swing.JButton btPesquisar;
    private javax.swing.JButton btPesquisarFuncionario;
    private javax.swing.JButton btSalvar;
    private javax.swing.JButton btSalvar2;
    private javax.swing.JCheckBox cbAdministrador;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLFuncionario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator17;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JPasswordField tfConfirmaSenha;
    private javax.swing.JTextField tfFuncionario;
    private javax.swing.JPasswordField tfSenha;
    private javax.swing.JTextField tfUsuario;
    // End of variables declaration//GEN-END:variables
}
